import { Archive, ChevronDown, ChevronLeft, FolderPlus, FolderTree, Pencil, Trash2, X } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { useFinance } from '../application/store'
import { GroupCascader } from '../components/GroupCascader'
import { useToast } from '../components/ToastProvider'
import type { AccountGroup, Holding } from '../domain/types'

export function AccountGroups(){
  const finance=useFinance();const toast=useToast();const {state}=finance
  const groups=(state.accountGroups??[]).filter(g=>g.status==='active');const assets=state.holdings.filter(a=>!a.archived);const roots=useMemo(()=>groups.filter(g=>!g.parentId||!groups.some(p=>p.id===g.parentId)).sort((a,b)=>a.name.localeCompare(b.name,'ar')),[groups]);const [expanded,setExpanded]=useState<Set<string>>(new Set(roots.map(r=>r.id)));const [editing,setEditing]=useState<AccountGroup|null>(null);const [newOpen,setNewOpen]=useState(false)
  const toggle=(id:string)=>setExpanded(p=>{const n=new Set(p);n.has(id)?n.delete(id):n.add(id);return n})
  return <div className="page-stack"><section className="section-intro"><div><span className="eyebrow">GROUP → ASSET</span><h2>مجموعات الأصول</h2><p>المجموعة هي الحاوية التنظيمية الوحيدة. أنشئ أي شجرة تريدها، ثم انقل الأصول بينها بلا أي حركة مالية.</p></div><button className="primary" onClick={()=>setNewOpen(true)}><FolderPlus size={16}/> إضافة مجموعة</button></section>
    <section className="panel category-tree-panel"><div className="panel-head"><div><span>شجرتك</span><h2>{groups.length} مجموعة • {assets.length} أصل</h2></div></div>{roots.length? <div className="category-tree">{roots.map(g=><GroupNode key={g.id} group={g}/>)}</div>:<div className="empty-preview"><FolderTree/><strong>لا توجد مجموعات</strong><span>يمكن أن تبقى الأصول من الجذر، أو أن تنشئ مجموعات مثل البنوك والمعادن والعقارات.</span></div>}
      {assets.filter(a=>!a.groupId||!groups.some(g=>g.id===a.groupId)).length>0&&<div className="asset-subgroup"><div className="asset-subgroup-title"><span>أصول من الجذر</span></div>{assets.filter(a=>!a.groupId||!groups.some(g=>g.id===a.groupId)).map(a=><AssetRow key={a.id} asset={a}/>)}</div>}
    </section>
    {(newOpen||editing)&&<GroupEditor group={editing} groups={groups} onClose={()=>{setNewOpen(false);setEditing(null)}} onSave={(name,parentId,description)=>{try{if(editing)finance.updateAccountGroup({id:editing.id,name,parentId:parentId||undefined,description:description||undefined});else finance.createAccountGroup({name,parentId:parentId||undefined,description:description||undefined});toast.success(editing?'تم تعديل المجموعة.':'تم إنشاء المجموعة.');setNewOpen(false);setEditing(null)}catch(e){toast.error(e instanceof Error?e.message:'تعذر حفظ المجموعة')}}}/>} 
  </div>

  function GroupNode({group}:{group:AccountGroup}){const children=groups.filter(g=>g.parentId===group.id).sort((a,b)=>a.name.localeCompare(b.name,'ar'));const direct=assets.filter(a=>a.groupId===group.id).sort((a,b)=>a.name.localeCompare(b.name,'ar'));const open=expanded.has(group.id);return <div className="category-node-wrap"><div className="category-node"><button className="category-branch" onClick={()=>toggle(group.id)}>{children.length||direct.length?(open?<ChevronDown size={14}/>:<ChevronLeft size={14}/>):<span className="tree-leaf-dot"/>}</button><div className="category-node-main"><div><strong>{group.name}</strong><span>{direct.length} أصل • {children.length} مجموعة فرعية</span></div></div><div className="category-node-actions"><button title="تعديل" onClick={()=>setEditing(group)}><Pencil size={14}/></button><button title="حذف/أرشفة" onClick={()=>{if(!window.confirm(`حذف مجموعة «${group.name}»؟ يجب أن تكون فارغة أولًا.`))return;try{finance.archiveAccountGroup(group.id);toast.success('تم حذف المجموعة من الشجرة.')}catch(e){toast.error(e instanceof Error?e.message:'تعذر حذف المجموعة')}}}><Archive size={14}/></button></div></div>{open&&<div className="category-children">{direct.map(a=><AssetRow key={a.id} asset={a}/>)}{children.map(c=><GroupNode key={c.id} group={c}/>)}</div>}</div>}
  function AssetRow({asset}:{asset:Holding}){return <div className="account-manage-row"><div><strong>{asset.name}</strong><span>{asset.quantity.toLocaleString('ar-SA')} {asset.nativeUnit} • {asset.symbol}</span></div><label><span>نقل إلى</span><select value={asset.groupId??''} onChange={e=>{try{finance.moveAssetToGroup(asset.id,e.target.value||undefined);toast.success(`تم نقل «${asset.name}» تنظيميًا بلا حركة مالية.`)}catch(error){toast.error(error instanceof Error?error.message:'تعذر النقل')}}}><option value="">من الجذر</option>{groups.map(g=><option key={g.id} value={g.id}>{groupPath(g.id)}</option>)}</select></label><button className="ghost small" onClick={()=>{const why=window.prompt(`سبب حذف «${asset.name}»؟`);if(!why)return;try{finance.deleteAsset(asset.id,why);toast.success('تم حذف/إلغاء الأصل بأمان.')}catch(e){toast.error(e instanceof Error?e.message:'تعذر حذف الأصل')}}}><Trash2 size={14}/> حذف</button></div>}
  function groupPath(id:string){const names:string[]=[];const seen=new Set<string>();let cur=groups.find(g=>g.id===id);while(cur&&!seen.has(cur.id)){seen.add(cur.id);names.unshift(cur.name);cur=cur.parentId?groups.find(g=>g.id===cur!.parentId):undefined}return names.join(' ← ')}
}

function GroupEditor({group,groups,onClose,onSave}:{group:AccountGroup|null;groups:AccountGroup[];onClose:()=>void;onSave:(name:string,parentId:string,description:string)=>void}){const [name,setName]=useState(group?.name??'');const [parent,setParent]=useState(group?.parentId??'');const [description,setDescription]=useState(group?.description??'');const blocked=group?new Set([group.id]):new Set<string>();const eligible=groups.filter(g=>!blocked.has(g.id));return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="expense-modal category-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={onClose}><X size={18}/></button><div className="panel-head"><div><span>تنظيم فقط</span><h2>{group?'تعديل المجموعة':'مجموعة جديدة'}</h2></div></div><form className="trade-form" onSubmit={(e:FormEvent)=>{e.preventDefault();onSave(name,parent,description)}}><label><span>اسم المجموعة</span><input autoFocus value={name} onChange={e=>setName(e.target.value)}/></label><GroupCascader groups={eligible} value={parent} onChange={setParent} label="المجموعة الأب"/><label><span>الوصف</span><input value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="primary wide" type="submit">حفظ</button></form></section></div>}
