import { Pencil, Trash2, X } from 'lucide-react'
import { useState, type FormEvent } from 'react'
import { useFinance } from '../application/store'
import { GroupCascader } from '../components/GroupCascader'
import { useToast } from '../components/ToastProvider'
import { assetTypeCatalog, type AssetTypeId } from '../domain/assetCatalog'
import type { ExpenseNecessity, LedgerTransaction } from '../domain/types'

const money=new Intl.NumberFormat('ar-SA',{maximumFractionDigits:2})
const toLocal=(iso:string)=>{const d=new Date(iso);const local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,16)}
const num=(v:string)=>Number(v.replace(/,/g,''))
const kindLabel=(k:string)=>({opening:'افتتاحي',income:'دخل',expense:'مصروف',real_transfer:'نقل',asset_purchase:'شراء أصل',asset_sale:'بيع أصل',conversion:'تحويل',reconciliation:'تسوية',refund:'استرداد',ownership_event:'ملكية',liability_creation:'التزام',liability_payment:'سداد',allocation_settlement:'تسوية تخصيص'} as Record<string,string>)[k]??k

export function Ledger(){
 const finance=useFinance();const toast=useToast();const {state}=finance;const [editing,setEditing]=useState<LedgerTransaction|null>(null);const activeAssets=state.holdings.filter(a=>!a.archived);const assetName=(id?:string)=>id?activeAssets.find(a=>a.id===id)?.name??'أصل غير موجود':'—'
 return <div className="page-stack"><section className="section-intro"><div><span className="eyebrow">AUDITED TRANSACTIONS</span><h2>الحركات</h2><p>كل حركة أدخلتها قابلة للتصحيح أو الإلغاء. التعديل المالي يعكس الأثر القديم ثم يعيد تطبيق التصحيح، والحذف يعكس الأثر ويحفظ الحركة كملغاة.</p></div></section><section className="panel"><div className="ledger-list">{state.ledger.length===0?<div className="empty-preview"><strong>لا توجد حركات</strong></div>:state.ledger.map(tx=><div className={`ledger-card ${tx.status==='voided'?'voided':''}`} key={tx.id}><div className="ledger-card-main"><div><strong>{tx.title}</strong><span>{kindLabel(tx.kind)} • {new Date(tx.at).toLocaleString('ar-SA')} • v{tx.version}{tx.status==='voided'?' • ملغاة':''}</span></div><div><strong>{money.format(tx.amountSar)} ر.س</strong><span>{tx.sourceHoldingId?`من: ${assetName(tx.sourceHoldingId)}`:''}{tx.targetHoldingId?` • إلى: ${assetName(tx.targetHoldingId)}`:''}</span></div></div>{tx.note&&<p>{tx.note}</p>}<div className="ledger-actions">{tx.status==='posted'&&<><button className="ghost small" onClick={()=>setEditing(tx)}><Pencil size={14}/> تعديل / تصحيح</button><button className="ghost small danger" onClick={()=>{const why=window.prompt(`سبب حذف/إلغاء «${tx.title}»؟`);if(!why)return;try{finance.voidTransaction(tx.id,why);toast.success('تم عكس الحركة وإلغاؤها مع حفظ سجل التدقيق.')}catch(e){toast.error(e instanceof Error?e.message:'تعذر إلغاء الحركة')}}}><Trash2 size={14}/> حذف / إلغاء</button></>}{tx.revisions.length>0&&<span className="ledger-revision-count">{tx.revisions.length} مراجعات</span>}</div></div>)}</div></section>{editing&&<TransactionEditor tx={editing} onClose={()=>setEditing(null)}/>}</div>
}

function TransactionEditor({tx,onClose}:{tx:LedgerTransaction;onClose:()=>void}){
 const finance=useFinance();const toast=useToast();const {state}=finance;const assets=state.holdings.filter(a=>!a.archived);const cash=assets.filter(a=>a.kind==='cash');const owners=state.parties.filter(p=>p.type==='self'||p.type==='person');const groups=(state.accountGroups??[]).filter(g=>g.status==='active');const categories=(state.expenseCategories??[]).filter(c=>c.status==='active');const beneficiaries=(state.expenseBeneficiaries??[]).filter(b=>b.status==='active');const portfolios=state.portfolios.filter(p=>p.status==='active')
 const [reason,setReason]=useState('تصحيح إدخال المستخدم');const [at,setAt]=useState(toLocal(tx.at));const [title,setTitle]=useState(tx.title);const [note,setNote]=useState(tx.note??'');const [ownerId,setOwner]=useState(tx.ownerId)
 const [source,setSource]=useState(tx.sourceHoldingId??'');const [target,setTarget]=useState(tx.targetHoldingId??'');const [quantity,setQuantity]=useState(String(tx.sourceQuantity??tx.targetQuantity??0))
 const u=tx.userInput?.kind==='asset_purchase'?tx.userInput:undefined;const targetAsset=assets.find(a=>a.id===tx.targetHoldingId);const [groupId,setGroup]=useState(u?.targetGroupId??targetAsset?.groupId??'');const [amountPaid,setAmountPaid]=useState(String(u?.amountPaid??tx.sourceQuantity??0));const [assetTypeId,setAssetType]=useState<AssetTypeId>((u?.assetTypeId as AssetTypeId)||'other');const [assetName,setAssetName]=useState(u?.name??targetAsset?.name??'');const [symbol,setSymbol]=useState(u?.symbol??targetAsset?.symbol??'');const [purchaseQty,setPurchaseQty]=useState(String(u?.quantity??tx.targetQuantity??0));const [fees,setFees]=useState(String(u?.extraCostsSar??tx.feesSar??0));const [market,setMarket]=useState(String(u?.marketUnitPriceSar??targetAsset?.marketPriceSar??0));const [location,setLocation]=useState(u?.location??targetAsset?.location??'')
 const [categoryId,setCategory]=useState(tx.expenseCategoryId??'');const [beneficiaryId,setBeneficiary]=useState(tx.expenseBeneficiaryId??'');const [necessity,setNecessity]=useState<ExpenseNecessity|''>(tx.expenseNecessity??'');const [portfolioId,setPortfolio]=useState(tx.portfolioId??'')
 const closeSuccess=()=>{toast.success('تم تصحيح الحركة وحفظ النسخة السابقة في سجل المراجعات.');onClose()}
 const submit=(e:FormEvent)=>{e.preventDefault();try{const iso=new Date(at).toISOString();if(tx.kind==='asset_purchase'){finance.correctAssetPurchase({transactionId:tx.id,reason,at:iso,title,note:note||undefined,sourceHoldingId:source,ownerId,amountPaid:num(amountPaid),targetGroupId:groupId||undefined,assetTypeId,name:assetName,symbol:symbol||undefined,quantity:num(purchaseQty),extraCostsSar:num(fees||'0'),location:location||undefined,marketUnitPriceSar:num(market||'0')||undefined,marketSource:'user-correction'});closeSuccess();return}if(tx.kind==='opening'){finance.correctOpening({transactionId:tx.id,reason,at:iso,assetId:target,ownerId,quantity:num(quantity),title,note:note||undefined});closeSuccess();return}if(tx.kind==='income'){finance.correctIncome({transactionId:tx.id,reason,at:iso,assetId:target,ownerId,quantity:num(quantity),title,note:note||undefined});closeSuccess();return}if(tx.kind==='real_transfer'){finance.correctTransfer({transactionId:tx.id,reason,at:iso,sourceAssetId:source,targetAssetId:target,ownerId,quantity:num(quantity),title,note:note||undefined});closeSuccess();return}if(tx.kind==='expense'){finance.correctExpense({transactionId:tx.id,reason,at:iso,sourceAssetId:source,ownerId,quantity:num(quantity),expenseCategoryId:categoryId,portfolioId:portfolioId||undefined,expenseBeneficiaryId:beneficiaryId||undefined,expenseNecessity:necessity||undefined,title,note:note||undefined});closeSuccess();return}finance.reviseTransaction({transactionId:tx.id,reason,at:iso,title,note:note||undefined,expenseCategoryId:categoryId||undefined,expenseBeneficiaryId:beneficiaryId||undefined,expenseNecessity:necessity||undefined});closeSuccess()}catch(error){toast.error(error instanceof Error?error.message:'تعذر تصحيح الحركة')}}
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="expense-modal transaction-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={onClose}><X size={18}/></button><div className="panel-head"><div><span>{kindLabel(tx.kind)} • v{tx.version}</span><h2>تصحيح الحركة</h2><span>التصحيح المالي يعكس الإسقاط السابق ويعيد تطبيق البيانات الجديدة على نفس Transaction ID.</span></div></div><form className="trade-form" onSubmit={submit}><div className="field-grid"><label><span>العنوان</span><input value={title} onChange={e=>setTitle(e.target.value)}/></label><label><span>التاريخ والوقت</span><input type="datetime-local" value={at} onChange={e=>setAt(e.target.value)}/></label></div><label><span>سبب التصحيح</span><input required value={reason} onChange={e=>setReason(e.target.value)}/></label><label><span>ملاحظة</span><input value={note} onChange={e=>setNote(e.target.value)}/></label>
 {['opening','income','expense','real_transfer','asset_purchase'].includes(tx.kind)&&<label><span>المالك</span><select value={ownerId} onChange={e=>setOwner(e.target.value)}>{owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
 {tx.kind==='asset_purchase'&&<><label><span>أصل الدفع</span><select value={source} onChange={e=>setSource(e.target.value)}>{cash.map(a=><option key={a.id} value={a.id}>{a.name} — {a.symbol}</option>)}</select></label><div className="field-grid"><label><span>المبلغ المدفوع</span><input value={amountPaid} onChange={e=>setAmountPaid(e.target.value)} inputMode="decimal"/></label><label><span>نوع الأصل</span><select value={assetTypeId} onChange={e=>setAssetType(e.target.value as AssetTypeId)}>{assetTypeCatalog.map(x=><option key={x.id} value={x.id}>{x.groupLabel} — {x.label}</option>)}</select></label></div><div className="field-grid"><label><span>اسم الأصل</span><input value={assetName} onChange={e=>setAssetName(e.target.value)}/></label><label><span>الرمز</span><input value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())}/></label></div><div className="field-grid three"><label><span>الكمية</span><input value={purchaseQty} onChange={e=>setPurchaseQty(e.target.value)} inputMode="decimal"/></label><label><span>الرسوم</span><input value={fees} onChange={e=>setFees(e.target.value)} inputMode="decimal"/></label><label><span>القيمة الحالية للوحدة</span><input value={market} onChange={e=>setMarket(e.target.value)} inputMode="decimal"/></label></div><GroupCascader groups={groups} value={groupId} onChange={setGroup} label="تموضع الأصل الناتج"/><label><span>الموقع</span><input value={location} onChange={e=>setLocation(e.target.value)}/></label></>}
 {tx.kind==='opening'&&<><label><span>الأصل</span><select value={target} onChange={e=>setTarget(e.target.value)}>{assets.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label><span>الرصيد / الكمية الافتتاحية</span><input value={quantity} onChange={e=>setQuantity(e.target.value)} inputMode="decimal"/></label></>}
 {tx.kind==='income'&&<><label><span>الأصل النقدي المستلم</span><select value={target} onChange={e=>setTarget(e.target.value)}>{cash.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label><span>المبلغ</span><input value={quantity} onChange={e=>setQuantity(e.target.value)} inputMode="decimal"/></label></>}
 {tx.kind==='real_transfer'&&<><div className="field-grid"><label><span>من أصل</span><select value={source} onChange={e=>setSource(e.target.value)}>{cash.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label><span>إلى أصل</span><select value={target} onChange={e=>setTarget(e.target.value)}>{cash.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label></div><label><span>المبلغ</span><input value={quantity} onChange={e=>setQuantity(e.target.value)} inputMode="decimal"/></label></>}
 {tx.kind==='expense'&&<><label><span>أصل الدفع</span><select value={source} onChange={e=>setSource(e.target.value)}>{cash.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label><span>المبلغ</span><input value={quantity} onChange={e=>setQuantity(e.target.value)} inputMode="decimal"/></label><div className="field-grid"><label><span>بند الصرف</span><select value={categoryId} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label><span>المستفيد</span><select value={beneficiaryId} onChange={e=>setBeneficiary(e.target.value)}><option value="">غير محدد</option>{beneficiaries.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div><div className="field-grid"><label><span>الضرورة</span><select value={necessity} onChange={e=>setNecessity(e.target.value as ExpenseNecessity|'')}><option value="">غير محدد</option><option value="obligation">التزام ملزم</option><option value="essential">أساسي</option><option value="flexible">مرن</option><option value="discretionary">كمالي</option></select></label><label><span>المحفظة</span><select value={portfolioId} onChange={e=>setPortfolio(e.target.value)}><option value="">السيولة الحرة</option>{portfolios.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div></>}
 {!['opening','income','expense','real_transfer','asset_purchase'].includes(tx.kind)&&<div className="operation-rule"><span>هذه الحركة تدعم الآن تعديل البيانات الوصفية والتاريخ. تغيير أثرها المالي سيحتاج Replay الخاص بنوعها؛ النظام لن يخمن أو يفسد الأرصدة.</span></div>}
 <button className="primary wide" type="submit">حفظ التصحيح</button></form>{tx.revisions.length>0&&<div className="revision-history"><strong>سجل المراجعات</strong>{[...tx.revisions].reverse().map((r,i)=><div key={`${r.version}-${i}`}><span>v{r.version} • {new Date(r.changedAt).toLocaleString('ar-SA')}</span><small>{r.reason}</small></div>)}</div>}</section></div>
}
