import { Banknote, Boxes, CircleAlert, ReceiptText, UserRound } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import { useFinance } from '../application/store'
import { useToast } from '../components/ToastProvider'
import { availableQuantity, ownerQuantity, round2 } from '../domain/finance'
import type { ExpenseCategory, ExpenseNecessity } from '../domain/types'
import { SELF_ID } from '../data/seed'

const money = new Intl.NumberFormat('ar-SA', { maximumFractionDigits: 2 })
const necessityLabels: Record<ExpenseNecessity, string> = { obligation: 'التزام ملزم', essential: 'أساسي', flexible: 'مرن', discretionary: 'كمالي / اختياري' }
function categoryPath(all: ExpenseCategory[], id?: string): ExpenseCategory[] { if (!id) return []; const result:ExpenseCategory[]=[];let current=all.find(c=>c.id===id);const seen=new Set<string>();while(current&&!seen.has(current.id)){seen.add(current.id);result.unshift(current);current=current.parentId?all.find(c=>c.id===current!.parentId):undefined}return result }
function effectiveNecessity(all: ExpenseCategory[], id?: string): ExpenseNecessity | undefined { const path=categoryPath(all,id);for(let i=path.length-1;i>=0;i-=1)if(path[i].defaultNecessity)return path[i].defaultNecessity;return undefined }

export function SpendExpense(){
  const finance=useFinance();const toast=useToast();const {state}=finance
  const owners=state.parties.filter(p=>p.type==='self'||p.type==='person');const categories=(state.expenseCategories??[]).filter(c=>c.status==='active');const beneficiaries=(state.expenseBeneficiaries??[]).filter(b=>b.status==='active')
  const [ownerId,setOwnerId]=useState(owners.find(o=>o.id===SELF_ID)?.id??owners[0]?.id??'');const cashAssets=useMemo(()=>state.holdings.filter(h=>!h.archived&&h.kind==='cash'&&ownerQuantity(h,ownerId)>0),[state.holdings,ownerId]);const portfolios=state.portfolios.filter(p=>p.status==='active'&&p.ownerIds.includes(ownerId));const [sourceHoldingId,setSourceHoldingId]=useState('');const [categoryId,setCategoryId]=useState('');const [portfolioId,setPortfolioId]=useState('');const [beneficiaryId,setBeneficiaryId]=useState('');const [necessityOverride,setNecessityOverride]=useState<ExpenseNecessity|''>('');const [quantity,setQuantity]=useState('');const [title,setTitle]=useState('');const [note,setNote]=useState('')
  const source=cashAssets.find(h=>h.id===sourceHoldingId);const amount=Number(quantity.replace(/,/g,''))||0;const amountSar=source?round2(amount*source.marketPriceSar):0;const freeQty=source?availableQuantity(state,source.id,ownerId):0;const portfolioValue=portfolioId?round2(state.portfolioSlices.filter(s=>s.portfolioId===portfolioId&&s.ownerId===ownerId).reduce((sum,s)=>{const h=state.holdings.find(x=>x.id===s.holdingId&&!x.archived);return sum+(h?s.quantity*h.marketPriceSar:0)},0)):0;const inheritedNecessity=effectiveNecessity(categories,categoryId);const finalNecessity=necessityOverride||inheritedNecessity;const beneficiary=beneficiaries.find(b=>b.id===beneficiaryId);const prerequisitesMissing=categories.length===0||cashAssets.length===0
  const submit=(event:FormEvent)=>{event.preventDefault();try{finance.spendExpense({sourceHoldingId,ownerId,quantity:amount,expenseCategoryId:categoryId,portfolioId:portfolioId||undefined,expenseBeneficiaryId:beneficiaryId||undefined,expenseNecessity:necessityOverride||undefined,title:title||undefined,note:note||undefined});setQuantity('');setTitle('');setNote('');setNecessityOverride('');toast.success(portfolioId?'تم تسجيل المصروف وخصمه من الأصل النقدي والمحفظة.':'تم تسجيل المصروف وخصمه من الأصل النقدي.')}catch(error){toast.error(error instanceof Error?error.message:'تعذر تسجيل المصروف')}}
  return <div className="page-stack"><section className="section-intro"><div><span className="eyebrow">WHAT + SOURCE ASSET + WHY + WHO</span><h2>تسجيل مصروف</h2><p>بند الصرف يحدد «على ماذا؟»، أصل الدفع «من أين خرج المال؟»، المحفظة «لأي غرض؟»، والمستفيد «لصالح من؟».</p></div></section>{prerequisitesMissing&&<section className="panel prerequisite-note"><CircleAlert size={20}/><div><strong>قبل أول مصروف</strong><p>{categories.length===0?'أنشئ بند صرف واحدًا على الأقل. ':''}{cashAssets.length===0?'وأنشئ أصلًا نقديًا ذا رصيد.':''}</p></div></section>}
  <section className="operation-workspace"><div className="operation-form-panel"><div className="panel operation-form"><div className="panel-head"><div><span>حركة مالية فعلية</span><h2>بيانات عملية الصرف</h2><span>الخصم يتم من الأصل النقدي مباشرة؛ المجموعة التنظيمية لا تدخل في القيد.</span></div><ReceiptText size={18}/></div><form className="trade-form" onSubmit={submit}>
  <div className="field-grid"><label><span>المالك</span><select value={ownerId} onChange={e=>{setOwnerId(e.target.value);setSourceHoldingId('');setPortfolioId('')}}>{owners.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label><span>المستفيد</span><select value={beneficiaryId} onChange={e=>setBeneficiaryId(e.target.value)}><option value="">غير محدد</option>{beneficiaries.map(b=><option key={b.id} value={b.id}>{b.name} — {b.kind==='group'?'مجموعة':'فرد'}</option>)}</select><small>المستفيد مستقل عن المالك والدافع.</small></label></div>
  <ExpenseCategoryCascader all={categories} selectedId={categoryId} onChange={id=>{setCategoryId(id);setNecessityOverride('')}}/>
  <label><span>درجة الضرورة لهذه العملية</span><select value={necessityOverride} onChange={e=>setNecessityOverride(e.target.value as ExpenseNecessity|'')}><option value="">حسب البند{inheritedNecessity?` — ${necessityLabels[inheritedNecessity]}`:' — غير مصنف'}</option><option value="obligation">التزام ملزم</option><option value="essential">أساسي</option><option value="flexible">مرن / قابل للضبط</option><option value="discretionary">كمالي / اختياري</option></select></label>
  <label><span>أصل الدفع</span><select value={sourceHoldingId} onChange={e=>setSourceHoldingId(e.target.value)}><option value="">اختر أصلًا نقديًا</option>{cashAssets.map(h=><option key={h.id} value={h.id}>{h.name} — {ownerQuantity(h,ownerId).toLocaleString('ar-SA')} {h.nativeUnit}</option>)}</select><small>{source?`المتاح الحر: ${freeQty.toLocaleString('ar-SA')} ${source.nativeUnit}`:'اختر الأصل الذي خرج منه المال فعليًا.'}</small></label>
  <div className="field-grid"><label><span>الكمية المصروفة {source?`(${source.nativeUnit})`:''}</span><input value={quantity} onChange={e=>setQuantity(e.target.value)} inputMode="decimal" placeholder="0"/></label><label><span>المحفظة</span><select value={portfolioId} onChange={e=>setPortfolioId(e.target.value)}><option value="">بلا محفظة — من السيولة الحرة</option>{portfolios.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><small>{portfolioId?`الرصيد الاقتصادي المخصص: ${money.format(portfolioValue)} ر.س`:'لن يُستهلك أي تخصيص محفظة.'}</small></label></div>
  <div className="field-grid"><label><span>عنوان مختصر</span><input value={title} onChange={e=>setTitle(e.target.value)}/></label><label><span>ملاحظة</span><input value={note} onChange={e=>setNote(e.target.value)}/></label></div><div className="inline-preview"><span>القيمة بالتقارير</span><strong>{money.format(amountSar)} ر.س</strong><small>{finalNecessity?`${necessityLabels[finalNecessity]}${beneficiary?` • المستفيد: ${beneficiary.name}`:''}`:(beneficiary?`المستفيد: ${beneficiary.name}`:'—')}</small></div><button className="primary wide" type="submit" disabled={prerequisitesMissing||!sourceHoldingId||!categoryId}>تسجيل المصروف</button></form></div></div>
  <aside className="operation-help expense-explain"><Banknote size={20}/><strong>أبعاد الحركة</strong><div className="expense-dimension"><b>WHAT</b><span>{categoryPath(categories,categoryId).map(c=>c.name).join(' ← ')||'بند الصرف'}</span></div><div className="expense-dimension"><b>SOURCE</b><span>{source?.name??'أصل الدفع'}</span></div><div className="expense-dimension"><b>WHY</b><span>{portfolioId?state.portfolios.find(p=>p.id===portfolioId)?.name:'السيولة الحرة'}</span></div><div className="expense-dimension"><b>WHO</b><span>{beneficiary?.name??'غير محدد'}</span></div><div className="operation-rule"><UserRound size={15}/><span>المستفيد لا يغير الملكية.</span></div><div className="operation-rule"><Boxes size={15}/><span>نقل الأصل بين المجموعات لا يغير هذه الحركة.</span></div></aside></section></div>
}

function ExpenseCategoryCascader({all,selectedId,onChange}:{all:ExpenseCategory[];selectedId:string;onChange:(id:string)=>void}){const path=categoryPath(all,selectedId);const roots=all.filter(c=>!c.parentId||!all.some(p=>p.id===c.parentId));const levels:ExpenseCategory[][]=[roots];path.forEach(node=>{const children=all.filter(c=>c.parentId===node.id);if(children.length)levels.push(children)});const choose=(level:number,value:string)=>{if(!value){const next=path.slice(0,level);onChange(next[next.length-1]?.id??'');return}const chosen=all.find(c=>c.id===value);if(chosen)onChange(chosen.id)};return <div className="parent-cascader expense-category-cascader"><div className="cascader-label"><span>بند الصرف</span><strong>{path.length?path.map(c=>c.name).join(' ← '):'اختر من الشجرة'}</strong></div><div className="cascader-levels">{levels.map((options,index)=><label key={index}><span>المستوى {index+1}</span><select value={path[index]?.id??''} onChange={e=>choose(index,e.target.value)}><option value="">{index===0?'اختر بندًا رئيسيًا':'اكتفِ بالمستوى السابق'}</option>{options.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>)}</div></div>}
