import type { ExpenseNecessity, FinanceState, LedgerTransaction, TransactionRevision } from '../domain/types'
import { spendExpense } from './expenses'
import { addIncomeToAsset, setAssetOpeningBalance, transferBetweenAssets } from './assetTransactions'
import { voidTransaction } from './transactionVoids'

const now=()=>new Date().toISOString()
function snapshot(tx:LedgerTransaction):TransactionRevision['snapshot']{return{at:tx.at,title:tx.title,amountSar:tx.amountSar,ownerId:tx.ownerId,sourceHoldingId:tx.sourceHoldingId,targetHoldingId:tx.targetHoldingId,sourceQuantity:tx.sourceQuantity,targetQuantity:tx.targetQuantity,exchangeRate:tx.exchangeRate,feesSar:tx.feesSar,realizedGainLossSar:tx.realizedGainLossSar,note:tx.note,portfolioId:tx.portfolioId,expenseCategoryId:tx.expenseCategoryId,expenseNecessity:tx.expenseNecessity,expenseBeneficiaryId:tx.expenseBeneficiaryId,userInput:tx.userInput}}
function prepare(state:FinanceState,tx:LedgerTransaction,reason:string){const reversed=voidTransaction(state,tx.id,reason);return{...reversed,ledger:reversed.ledger.filter(x=>x.id!==tx.id)}}
function preserve(state:FinanceState,current:LedgerTransaction,generated:LedgerTransaction,reason:string,at:string,title?:string,note?:string){const revision:TransactionRevision={version:current.version,changedAt:now(),reason,snapshot:snapshot(current)};const corrected:LedgerTransaction={...generated,id:current.id,version:current.version+1,revisions:[...current.revisions,revision],at,title:title?.trim()||generated.title,note:note?.trim()||generated.note};return{...state,ledger:state.ledger.map(tx=>tx.id===generated.id?corrected:tx)}}
function validAt(at:string){const d=new Date(at);if(Number.isNaN(d.getTime()))throw new Error('التاريخ غير صالح');return d.toISOString()}

export interface CorrectOpeningInput{transactionId:string;reason:string;at:string;assetId:string;ownerId:string;quantity:number;title?:string;note?:string}
export function correctOpening(state:FinanceState,input:CorrectOpeningInput){const current=state.ledger.find(x=>x.id===input.transactionId);if(!current||current.kind!=='opening'||current.status!=='posted')throw new Error('الحالة الافتتاحية غير موجودة أو غير نشطة');if(!input.reason.trim())throw new Error('سبب التصحيح مطلوب');const conflicting=state.ledger.find(x=>x.id!==current.id&&x.kind==='opening'&&x.status==='posted'&&x.targetHoldingId===input.assetId&&x.ownerId===input.ownerId);if(conflicting&&input.assetId!==current.targetHoldingId)throw new Error('للأصل الهدف حالة افتتاحية أخرى؛ صححها أو احذفها أولًا');let next=prepare(state,current,input.reason);const target=next.holdings.find(h=>h.id===input.assetId&&!h.archived);if(!target)throw new Error('الأصل الهدف غير موجود');next=setAssetOpeningBalance(next,{assetId:input.assetId,ownerId:input.ownerId,quantity:input.quantity,unitCostSar:target.marketPriceSar,title:input.title,reason:input.reason});const generated=next.ledger.find(x=>x.status==='posted'&&x.kind==='opening'&&x.targetHoldingId===input.assetId&&x.ownerId===input.ownerId);if(!generated)throw new Error('فشل إعادة إنشاء الحالة الافتتاحية');return preserve(next,current,generated,input.reason,validAt(input.at),input.title,input.note)}

export interface CorrectIncomeInput{transactionId:string;reason:string;at:string;assetId:string;ownerId:string;quantity:number;title?:string;note?:string}
export function correctIncome(state:FinanceState,input:CorrectIncomeInput){const current=state.ledger.find(x=>x.id===input.transactionId);if(!current||current.kind!=='income'||current.status!=='posted')throw new Error('حركة الدخل غير موجودة أو غير نشطة');if(!input.reason.trim())throw new Error('سبب التصحيح مطلوب');let next=prepare(state,current,input.reason);next=addIncomeToAsset(next,{assetId:input.assetId,ownerId:input.ownerId,quantity:input.quantity,title:input.title,note:input.note});const generated=next.ledger[0];return preserve(next,current,generated,input.reason,validAt(input.at),input.title,input.note)}

export interface CorrectTransferInput{transactionId:string;reason:string;at:string;sourceAssetId:string;targetAssetId:string;ownerId:string;quantity:number;title?:string;note?:string}
export function correctTransfer(state:FinanceState,input:CorrectTransferInput){const current=state.ledger.find(x=>x.id===input.transactionId);if(!current||current.kind!=='real_transfer'||current.status!=='posted')throw new Error('حركة النقل غير موجودة أو غير نشطة');if(!input.reason.trim())throw new Error('سبب التصحيح مطلوب');let next=prepare(state,current,input.reason);next=transferBetweenAssets(next,{sourceAssetId:input.sourceAssetId,targetAssetId:input.targetAssetId,ownerId:input.ownerId,quantity:input.quantity,note:input.note});const generated=next.ledger[0];return preserve(next,current,generated,input.reason,validAt(input.at),input.title,input.note)}

export interface CorrectExpenseInput{transactionId:string;reason:string;at:string;sourceAssetId:string;ownerId:string;quantity:number;expenseCategoryId:string;portfolioId?:string;expenseNecessity?:ExpenseNecessity;expenseBeneficiaryId?:string;title?:string;note?:string}
export function correctExpense(state:FinanceState,input:CorrectExpenseInput){const current=state.ledger.find(x=>x.id===input.transactionId);if(!current||current.kind!=='expense'||current.status!=='posted')throw new Error('حركة المصروف غير موجودة أو غير نشطة');if(!input.reason.trim())throw new Error('سبب التصحيح مطلوب');let next=prepare(state,current,input.reason);next=spendExpense(next,{sourceHoldingId:input.sourceAssetId,ownerId:input.ownerId,quantity:input.quantity,expenseCategoryId:input.expenseCategoryId,portfolioId:input.portfolioId,expenseNecessity:input.expenseNecessity,expenseBeneficiaryId:input.expenseBeneficiaryId,title:input.title,note:input.note});const generated=next.ledger[0];return preserve(next,current,generated,input.reason,validAt(input.at),input.title,input.note)}
